SUPABASE_URL = "https://sltglcuumressretwjij.supabase.co"
SUPABASE_PUBLIC_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsdGdsY3V1bXJlc3NyZXR3amlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NzY1NjMsImV4cCI6MjA2OTE1MjU2M30.RtFDpnT5rtNh4tKoOSUjWrirdwyxcHCQm1WW-Sy1XCM"
